export const KNOWLEDGE_BASE = `
What This Protocol Actually Is (Zero Hype Summary)
Rialo is a new Layer 1 blockchain network built by a company called Subzero Labs. Think of it like a super-smart computer system that runs on the internet, but it's decentralized—meaning no single boss controls it. What it does: It lets apps on the blockchain connect directly to real-world stuff, like weather data, stock prices, or even emails and phone numbers, without needing extra middlemen tools that can break or be hacked. Who needs it: Developers who want to build apps that feel like normal phone apps but with crypto security, like automatic insurance payouts if it rains too much, or betting on sports results that settle instantly. What real problem it solves: Most blockchains are like islands—they don't talk easily to the outside world, so apps feel slow and clunky. Rialo fixes that by making connections built-in, so everything is faster and less risky. Why it even exists: Crypto has grown, but to be useful in daily life—like sending money via email without a wallet—blockchains need to blend with the real internet. Rialo is trying to make that happen without the usual headaches.

Team, Origins & Backing (Trust Check)
Launch timeline: Subzero Labs came out of hiding (stealth mode) in August 2025 with a $20 million funding round. Their private test network (devnet) is live now for selected developers, but the full public launch isn't set yet—not confirmed publicly when mainnet goes live. Founder identities + past experience: Founders are Ade Adepoju and Lu Zhang. Ade was an early engineer at Mysten Labs (helped build Sui blockchain), worked on big systems at Netflix, and chips at AMD. Lu also from Mysten Labs, built Diem (Meta's old crypto project), AI stuff at Meta and Google. The team has people from Apple, Amazon, TikTok, Citadel, Solana, EigenLayer, Polkadot, Coinbase, and NEAR—solid mix of big tech and crypto pros. Investors / grants / ecosystem partners: Led by Pantera Capital, with Variant, Coinbase Ventures, Hashed, Susquehanna Crypto, Mysten Labs, Fabric Ventures, Flowdesk, Mirana Ventures. No grants mentioned publicly. Audits, GitHub activity, transparency signals: No audits confirmed publicly yet—project is early. GitHub for Subzero Labs isn't directly linked to Rialo code; one unrelated "subZero" GitHub exists, but nothing for Rialo protocol. Transparency: They share blog posts on their site, active on X (Twitter), but no open-source code visible yet—not confirmed publicly.

Technology Breakdown (Explain Like I’m Smart But Not Nerdy)
Rialo is built from scratch to handle real-life data without extra layers. Consensus: Not confirmed publicly—likely some form of proof-of-stake, but no details. Chain architecture: It's a Layer 1, meaning the base level where everything runs, using RISC-V (a flexible computer instruction set) for smart contracts—that's the code that runs apps. This makes it lightweight and powerful. Execution model: Event-driven, so apps react automatically to things happening, like a trigger when a stock price changes—no constant checking needed. Data availability: Built-in access to real-world data like weather or bank feeds directly in the code, no middle tools. Security model: Relies on primary sources for data (like official websites) instead of trusting reporters; privacy is default for sensitive info, using things like encrypted triggers. Interoperability: Works with Solana's virtual machine, so apps from there can move over easily; cross-chain messages without bridges. New innovations: Native web calls—smart contracts can talk to the internet directly over HTTPS, like fetching data from nfl.com for sports bets. What makes it different: Older blockchains focus on speed (transactions per second), but Rialo makes real-world connections native, so no oracles (those are like messengers that can lie or delay). It's like upgrading from a basic phone to a smartphone that connects everything seamlessly.

How It Works (Step-by-Step Flow)
Imagine you're betting on a cricket match outcome. Step 1: You create a market on Rialo app—say, "Will India win the next ODI?" You put money in a smart contract (like a locked box). Step 2: Others join, betting yes or no, and the contract holds all the money. Step 3: The contract points directly to a trusted source, like the official cricket website (espncricinfo.com), for the result—no waiting for someone to tell it. Step 4: When the match ends, the network checks the source automatically (using built-in web hooks, like an alert system). Step 5: If India wins, the contract sees it, unlocks the money, and pays out to the yes betters instantly. No human or extra tool involved—just direct from source to payout. For other stuff, like insurance: Step 1: Buy policy. Step 2: Contract watches weather site. Step 3: If rain floods your area, it triggers payout to your email or phone without you asking.

Real Benefits (Who Gains What)
Everyday retail users: You get apps that feel normal—no clunky wallets needed; send money via phone number, get instant settlements on bets or insurance, privacy for personal data like credit scores. Safer and faster than current crypto apps. Airdrop farmers: Early access to testnet could mean rewards if they launch incentives, but nothing confirmed—good for farming points through community tasks like raiding on X or creating content. Builders: Developers save time and money; no gluing extra tools for data—build once, run anywhere with Solana compatibility. Easier to make real apps like tokenized property or AI agents. Enterprises/institutions: Big companies get secure ways to handle real assets (like bonds or invoices) with auto-updates from banks or markets; compliant privacy for regulated stuff like finance or health. Chain partners or ecosystems: Other blockchains (like Solana) can integrate easily; partners get shared users and liquidity without bridges, growing the whole network.

Token & Economics (Only If Confirmed)
Not confirmed publicly. No token launched yet—no details on what it's for, supply, distribution, unlocks, revenue model, value loop, or long-term viability. Funding is through $20M investor money, but token economics aren't shared.

Competitor Benchmarking (Crypto Alchemy Style)
Top competitors: Solana (fast transactions, but needs extra tools for real data), Sui (from same founder roots, good for speed but not native web connects), Chainlink (oracle for data, but can be manipulated or slow). Technology: Rialo has built-in web calls vs. Solana's add-ons; better privacy than Sui. Cost & speed: Sub-second reactions like Web2, cheaper without middleware fees—beats Chainlink's delays. Security assumptions: Direct sources vs. Chainlink's reporters (less trust needed); stronger than Solana's for real-world stuff. Liquidity: Early stage, so low now vs. Solana's billions. Ecosystem depth: Small but growing with devnet; Solana has more apps. Dev adoption: Solana-compatible, so easy switch; attracting from big tech. User-base growth: New, but waitlist open—potential like Sui's fast rise. Realistic business use: Better for RWAs (real-world assets) than competitors, like auto-settling bonds. Compared to competitors, this protocol is just different: It's not chasing speed records; it's making blockchains useful for everyday real stuff, like blending crypto with your bank app. Why? Because it cuts out the messy extras, so apps work like Flipkart or Paytm, but decentralized—could win if real-world adoption kicks in.

Strengths, Weaknesses & Red Flags
Strengths: Super team from top companies, so they know how to build scalable stuff. Native connections mean fewer hacks or delays—great for bets or assets. Privacy built-in helps with rules in places like India. Early funding from big names shows trust. Event-driven means apps react fast, like real life. Weaknesses: Still early—private test only, no public use yet, so unproven at big scale. Relies on web sources, which could go down or change (though they say it's verifiable). No token means no way to stake or earn yet. Red flags: No audits public, code not open on GitHub—hard to check for bugs. If primary sources get hacked (rare, but possible), markets could fail. Launch delays common in crypto; if mainnet takes too long, hype dies.

Traction, Roadmap & Current Status
What’s live right now: Private devnet (test network) for selected developers to build and test apps. Integrations: Native with web services like APIs, emails, phones; Solana VM for easy app ports. Ecosystem progress: Waitlist open for public, community on Discord and X with roles like RialOPS for raiders. Growing posts about prediction markets and RWAs. Roadmap items: After private devnet, public testnet next (no date); then mainnet launch. Focus on more languages and features. Anything officially confirmed: $20M raise in Aug 2025, backed by Pantera etc. Blog posts on site about securing markets and RWAs. No hype—just building quietly.

Airdrop / Incentive Insight (If Applicable)
No confirmed incentive or airdrop plan. Community tasks like content creation or X raids give roles (e.g., RialOYAL for active users), which might lead to future rewards, but nothing official. Waitlist could position for early access, but no airdrop announced.
`;

export const SYSTEM_INSTRUCTION = `
You are the "Rialo Bot", a knowledgeable assistant for the Rialo protocol developed by Subzero Labs.
Your goal is to answer the user's question using ONLY the information found in the KNOWLEDGE_BASE provided in the prompt.
Tone: Professional, direct, technical but accessible ("Seamless by Design"). Avoid excessive emojis or "cute" language. Be precise and concise.
If the answer isn't in the knowledge base, politely state that the information is not currently available in your database.
`;

// Suggestions to help the user get started
export const SUGGESTED_QUESTIONS = [
  "What is Rialo?",
  "How does the tech work?",
  "Who are the founders?",
  "Is there a token?",
  "Comparison with Solana?"
];

// DEVELOPER: Add your Base64 encoded PDFs or Images here to "feed" them to the app firsthand.
export const SYSTEM_ATTACHMENTS: Array<{ mimeType: string; base64: string }> = [];
